// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
// / await Firebase.initializeApp(
// /   options: DefaultFirebaseOptions.currentPlatform,
// / );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaMIJsrR5A5DKa6eAs0sgoNbTWvT8I94s',
    appId: '1:328738057085:web:71b85e7f24b35682effa14',
    messagingSenderId: '328738057085',
    projectId: 'ci-cd-example-34b52',
    authDomain: 'ci-cd-example-34b52.firebaseapp.com',
    storageBucket: 'ci-cd-example-34b52.firebasestorage.app',
    measurementId: 'G-Y1ST0YLGHJ',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDp6cHKmxJ3J4si5mNa8lD5OI8XXkeUs_Q',
    appId: '1:328738057085:ios:f81fff8fd4b2de1ceffa14',
    messagingSenderId: '328738057085',
    projectId: 'ci-cd-example-34b52',
    storageBucket: 'ci-cd-example-34b52.firebasestorage.app',
    iosBundleId: 'com.example.ciCdExample',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCaMIJsrR5A5DKa6eAs0sgoNbTWvT8I94s',
    appId: '1:328738057085:web:5e81b704c7ea3136effa14',
    messagingSenderId: '328738057085',
    projectId: 'ci-cd-example-34b52',
    authDomain: 'ci-cd-example-34b52.firebaseapp.com',
    storageBucket: 'ci-cd-example-34b52.firebasestorage.app',
    measurementId: 'G-T6DERC0YMS',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDp6cHKmxJ3J4si5mNa8lD5OI8XXkeUs_Q',
    appId: '1:328738057085:ios:f81fff8fd4b2de1ceffa14',
    messagingSenderId: '328738057085',
    projectId: 'ci-cd-example-34b52',
    storageBucket: 'ci-cd-example-34b52.firebasestorage.app',
    iosBundleId: 'com.example.ciCdExample',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIH-aidRvESlR702TQldH5rSTA3HMvZ74',
    appId: '1:328738057085:android:f20b6a2c5bf30ae2effa14',
    messagingSenderId: '328738057085',
    projectId: 'ci-cd-example-34b52',
    storageBucket: 'ci-cd-example-34b52.firebasestorage.app',
  );
}
