

# this lane for distributing android version to firebase 
# to run this lane just type => fastlane android test_app_distribution
default_platform(:android)
platform :android do
  desc "Lane for Android Firebase App Distribution"
  lane :test_app_distribution do 
    sh "flutter clean"  
    sh "flutter pub get"
    sh "flutter build apk --release --no-tree-shake-icons"
    firebase_app_distribution(
      app:"1:328738057085:android:f20b6a2c5bf30ae2effa14",
      firebase_cli_token:ENV["FIRBASE_CLI_TOKEN"],
      android_artifact_type:"APK",
      android_artifact_path:"../build/app/outputs/flutter-apk/app-release.apk",
      testers:"mmoud2031@gmail.com",
      release_notes:"test fastlane for the first time."
      )
  end

end
